set_property SRC_FILE_INFO {cfile:{C:/Users/Asus/Vivado/led sw/led sw.srcs/constrs_1/imports/led sw/Arty-A7-35-Master.xdc} rfile:{../../../led sw.srcs/constrs_1/imports/led sw/Arty-A7-35-Master.xdc} id:1} [current_design]
set_property src_info {type:XDC file:1 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN A8    IOSTANDARD LVCMOS33 } [get_ports { sw }]; #IO_L12N_T1_MRCC_16 Sch=sw[0]
set_property src_info {type:XDC file:1 line:33 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN H5    IOSTANDARD LVCMOS33 } [get_ports { led }]; #IO_L24N_T3_35 Sch=led[4]
