webtalk_init -webtalk_dir C:/Users/Asus/OneDrive/Documentos/GitHub/Verilog_projects/Pynq/i2c_slave/i2c_slave.sim/sim_1/behav/xsim/xsim.dir/tb_i2c_start_stop_detector_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Jun  5 22:14:06 2025" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "93506e6e-d843-4a61-a977-36f44b87959b" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "56f48e9b58c642e289aaecb7af820fe1" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "17" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 7 3700U with Radeon Vega Mobile Gfx  " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2296 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "19.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "90 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.00_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "6712_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1889708841 -regid "" -xml C:/Users/Asus/OneDrive/Documentos/GitHub/Verilog_projects/Pynq/i2c_slave/i2c_slave.sim/sim_1/behav/xsim/xsim.dir/tb_i2c_start_stop_detector_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/Asus/OneDrive/Documentos/GitHub/Verilog_projects/Pynq/i2c_slave/i2c_slave.sim/sim_1/behav/xsim/xsim.dir/tb_i2c_start_stop_detector_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/Asus/OneDrive/Documentos/GitHub/Verilog_projects/Pynq/i2c_slave/i2c_slave.sim/sim_1/behav/xsim/xsim.dir/tb_i2c_start_stop_detector_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
